### ISSUE TITLE
cannot import system_arg from payload

### ISSUE THREAD

**Issue by Ar1ste1a** [chompie1337/SIGRed_RCE_PoC#12]
I am receiving this error after installing payload-api and running evildns.py. I have searched the init file for references to system_arg and every other file in the package but I cannot find the reference to this module. I noticed this is used in a  binary concatenation so it is likely just a string, do you have the string or are you able to point me to where to find it?

**Comment by chompie1337** [comment]
Please read the instructions in the readme. You need to run configure.py which will generate the payload

https://github.com/chompie1337/SIGRed_RCE_PoC/blob/ec0a20c619274d3d187adaa854ef51fd1042f90b/configure.py#L22
